version: "3.4"

services:
  challenge_php:
    build:
      context: .
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    depends_on:
      - challenge_database
    restart: unless-stopped
    volumes:
      - challenge_php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@challenge_database:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}

  challenge_caddy:
    build:
      context: .
      target: app_caddy
    depends_on:
      - challenge_php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
    restart: unless-stopped
    volumes:
      - challenge_php_socket:/var/run/php
      - challenge_caddy_data:/data
      - challenge_caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  challenge_database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-challenge_app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-challenge}
      POSTGRES_USER: ${POSTGRES_USER:-challenge}
    volumes:
      - challenge_db_data:/var/lib/postgresql/data:rw

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
volumes:
  challenge_php_socket:
  challenge_caddy_data:
  challenge_caddy_config:
  ###> doctrine/doctrine-bundle ###
  challenge_db_data:
  ###< doctrine/doctrine-bundle ###
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
