controllers_front:
    resource: ../src/Controller/Front
    type: attribute
    name_prefix: front_

controllers_back:
    resource: ../src/Controller/Back
    type: attribute
    name_prefix: back_
    prefix: /admin/

controller_api:
    resource: ../src/Controller/APIController.php
    type: attribute

controller_security:
    resource: ../src/Controller/SecurityController.php
    type: attribute
